import Head from 'next/head';
import { useMemo } from 'react';
import useLive from '@/hooks/useLive';
import useFixtures from '@/hooks/useFixtures';
import MatchList from '@/components/fixtures/MatchList';
import Loading from '@/components/Loading';
import { groupMatchesByLeague } from '@/utils/utils';

export default function Home() {
    const { data: all, isLoading: isLoading1 } = useLive();

    const { data: fixtures, isLoading: isLoading2 } = useFixtures();
    const live = useMemo(
        () => groupMatchesByLeague(all?.response),
        [all?.response]
    );

    const allFix = useMemo(
        () => groupMatchesByLeague(fixtures?.response),
        [fixtures?.response]
    );

    if (isLoading1 && isLoading2) {
        return (
            <div className="Matches">
                <Loading />
            </div>
        );
    }

    return (
        <>
            <Head>
                <title>Soccer App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="Matches">
                <MatchList live={live} all={allFix} />
            </div>
        </>
    );
}
